description: > # this means to ignore newlines until "baseurl:"
  About mobile payment, tech, programming.

exclude:
  - Gemfile
  - Gemfile.lock

future: true
date_format: "%b %-d, %Y"
title: 库胖MEDIA
